### PR TITLE
dashboard graphs: replace the dash with an underscrore

### PR DESCRIPTION
**Pull request by thekorn**

### CODE REVIEW

**Comment by kopf** [comment]
Seems a bit edelight-specific to be hardcoded, is it not? 

Alles gute nachträglich, übrigens! :cake:

**Comment by thekorn** [comment]
@kopf huhu, thanks so much ;)
I this not edelight specific at all. role names can contain a dash in chef, but whenever a name contains a dash pydot will crash with a 'pydot.InvocationException' exception, becasue names of graphs or subgraph cannot contain dashes, and kitches is using the role name as (sub)graph name
hope this makes sense, PEACE!

**Comment by kopf** [comment]
ahhh! gotcha. took it out of context.

**Comment by tobami** [comment]
So that's what was causing the `InvocationException`! Awesome Korn, way to go :smile: 

And hi there @kopf ! It's been a long time...

**Comment by thekorn** [comment]
two reviews of two of the best alumnis of my team, all I need to merge this pull request </new review policy>

**Pull request merged**
